[[MbedTLS]]
arch = "armv7l"
git-tree-sha1 = "f2ef98b4f23c9b3dec27d9c65218d83b31c0f9c5"
libc = "glibc"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "8b13b81cc8afcfea77d10112011bca9fa4658f0da0d715325b48ddd9a793ef16"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.arm-linux-gnueabihf.tar.gz"
[[MbedTLS]]
arch = "x86_64"
git-tree-sha1 = "1ee278227f735cf0fdd626da214cae2cbb761bb3"
libc = "glibc"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "73eb0a2f588d2724f56db1f69e7acd2e7862655db96477c3588b488c310ead59"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.x86_64-linux-gnu.tar.gz"
[[MbedTLS]]
arch = "aarch64"
git-tree-sha1 = "543a7eb074c60c9c67dcf374ba5fcb747b374978"
libc = "musl"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "7a2e6c5bc629f30c88c85b3489d8d4d0a2443d990694ebcee664e292445ad4db"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.aarch64-linux-musl.tar.gz"
[[MbedTLS]]
arch = "powerpc64le"
git-tree-sha1 = "654f284b489b798f444895b2625c3b8a9cb796e1"
libc = "glibc"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "202effd53c1aaa2592adcd20d2c83af6ec145d2bbd6acab30f293084fe14b6a9"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.powerpc64le-linux-gnu.tar.gz"
[[MbedTLS]]
arch = "x86_64"
git-tree-sha1 = "dc6e8d9bd41eba951c1bf1fb978546058b1cbf36"
os = "macos"

    [[MbedTLS.download]]
    sha256 = "280b760ed78bc29d9a2ab468495735213cc6a209228c6aa972aeda05d7bb7a6a"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.x86_64-apple-darwin14.tar.gz"
[[MbedTLS]]
arch = "x86_64"
git-tree-sha1 = "02ba095e95776250de3add6649f2eb38bd44fde0"
libc = "musl"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "28df3a27d12ba39d6ee5981ea4595356ad23857261076694be100932a675812f"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.x86_64-linux-musl.tar.gz"
[[MbedTLS]]
arch = "x86_64"
git-tree-sha1 = "440776d7e6c07bfbd7e24c92dfbf7d6bd8e9107e"
os = "windows"

    [[MbedTLS.download]]
    sha256 = "a1a78af0bd5b994aa837d784db2df67d4c0ffa373bf69888614a5c37120f415e"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.x86_64-w64-mingw32.tar.gz"
[[MbedTLS]]
arch = "i686"
git-tree-sha1 = "d298476ac6e817b36866e2b72dc67b1ef8c36877"
libc = "glibc"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "5f36bd1c2a095067b6e3c45e834fec0072ecd210ea8ba152cc5e57ae974ddf53"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.i686-linux-gnu.tar.gz"
[[MbedTLS]]
arch = "aarch64"
git-tree-sha1 = "09b8671eee44a417791b6a182f0c4cd5585a30e9"
libc = "glibc"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "19367fffbef2f97f341921859689f8327ce92de5a2949d292f216e7a1be811cf"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.aarch64-linux-gnu.tar.gz"
[[MbedTLS]]
arch = "i686"
git-tree-sha1 = "e8b7eda0e8c277fd9ccf67d17118bd9584a59493"
libc = "musl"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "0deb57307a9fe0bf5232b79e7d8991d3b1ac9ceb1837b770c0176204f49d4bfa"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.i686-linux-musl.tar.gz"
[[MbedTLS]]
arch = "x86_64"
git-tree-sha1 = "0e5efe07a4a5bdc9c06f69004d49180f3119d77b"
os = "freebsd"

    [[MbedTLS.download]]
    sha256 = "02d032806f93fd43995df61dccb56444ff0505d1f80ad45344145d50d0a1367c"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.x86_64-unknown-freebsd11.1.tar.gz"
[[MbedTLS]]
arch = "i686"
git-tree-sha1 = "6d92ff1be7e2b86e1c3a552ef1879b8b69b235b2"
os = "windows"

    [[MbedTLS.download]]
    sha256 = "bb11966c4c39774ef714b3fb2e70aa9f74bd8a9c812a1596f336b24649dc360c"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.i686-w64-mingw32.tar.gz"
[[MbedTLS]]
arch = "armv7l"
git-tree-sha1 = "4bfe5b9583491c363e291f0725cfda1386b89f21"
libc = "musl"
os = "linux"

    [[MbedTLS.download]]
    sha256 = "24bdc7677a0b6fb6d0683008788caa2de5d1ddd28b147ed373bf007f7ebebff2"
    url = "https://github.com/JuliaBinaryWrappers/MbedTLS_jll.jl/releases/download/MbedTLS-v2.16.0+1/MbedTLS.v2.16.0.arm-linux-musleabihf.tar.gz"
